# Generated by Django 4.1 on 2022-08-24 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='Market.items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Market.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='Market.items'),
        ),
        migrations.AlterField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(related_name='stores', to='Market.category'),
        ),
    ]
